### ISSUE TITLE
0.6.0 fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [any1/wayvnc#228]
Regressed by be42c8b7bf11. `ENODATA` is part of [STREAMS](https://en.wikipedia.org/wiki/STREAMS) (obsolete in [POSIX.1-2008](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/errno.h.html)) which are not supported on BSDs. NetBSD has `ENODATA` (unlike DragonFly, FreeBSD, OpenBSD) but uses it for [something unrelated](https://github.com/NetBSD/src/search?q=ENODATA+path%3Asys). What it's replaced with depends on context e.g.
- OpenBSD DRM defines `ENODATA` via `ENOTSUP`
- FreeBSD LinuxKPI defines `ENODATA` via `ECONNREFUSED`
- FreeBSD Linux syscall ABI defines `ENODATA` via `ENOATTR`
- FreeBSD OpenZFS defines `ENODATA` via `EINVAL`

```c
$ cc --version
FreeBSD clang version 15.0.7 (https://github.com/llvm/llvm-project.git llvmorg-15.0.7-0-g8dfdcc7b7bf6)
Target: x86_64-unknown-freebsd14.0
Thread model: posix
InstalledDir: /usr/bin

$ meson setup _build
$ meson compile -C _build
[...]
FAILED: wayvncctl.p/src_ctl-client.c.o
cc -Iwayvncctl.p -I. -I.. -I../include -I/usr/local/include -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=gnu11 -O0 -g '-DPROJECT_VERSION="0.6.0"' -D_GNU_SOURCE -DAML_UNSTABLE_API=1 -Wno-unused-parameter -Wno-missing-field-initializers '-DGIT_VERSION="v0.6.0-0-gb1c1ade (master)"' -MD -MQ wayvncctl.p/src_ctl-client.c.o -MF wayvncctl.p/src_ctl-client.c.o.d -o wayvncctl.p/src_ctl-client.c.o -c ../src/ctl-client.c
../src/ctl-client.c:226:11: error: use of undeclared identifier 'ENODATA'
                errno = ENODATA;
                        ^
../src/ctl-client.c:241:12: error: use of undeclared identifier 'ENODATA'
                        errno = ENODATA;
                                ^
../src/ctl-client.c:255:15: error: use of undeclared identifier 'ENODATA'
        if (errno != ENODATA)
                     ^
../src/ctl-client.c:295:25: error: use of undeclared identifier 'ENODATA'
                if (!root && errno != ENODATA)
                                      ^
4 errors generated.
```

**Comment by any1** [comment]
This is set and read internally, so it doesn't really matter how it's defined.  I think that maybe we shouldn't use `errno` like this. It would be better if we defined our own errors properly.

Looking at the man page, for `errno`, there isn't really anything there that applies properly. I think that `EAGAIN` is the closest match for what it actually means.

**Comment by any1** [comment]
I believe that I've taken care of this now with a new patch release. Thank you for a very thorough report!
