### PR TITLE
Unbreak build without libgbm

### PR DESCRIPTION
**Pull request by jbeich**
Regressed by 3742dc7144a8 (made `gbm` in meson.build optional). From [error log](https://github.com/any1/wayvnc/files/4984087/wayvnc-0.2.0.log):
```c
../src/buffer.c:25:10: fatal error: 'gbm.h' file not found
#include <gbm.h>
         ^~~~~~~
```
https://github.com/any1/wayvnc/blob/800b0d6cb76ac647615d409e6214861333fd122b/src/main.c#L56-L57

### CODE REVIEW

**Comment by any1** [comment]
Thanks!
